name: CI

env:
  IMAGE_NAME: xiangronglin/novel-worker

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - run: mvn install

      - name: Prepare for saving docker image
        if: github.event_name == 'push'
        run: mkdir docker

      - name: Save docker image as tar
        if: github.event_name == 'push'
        run: docker save ${{ env.IMAGE_NAME }} > docker/image.tar

      - name: Upload docker image tar as artifact
        uses: actions/upload-artifact@v2
        if: github.event_name == 'push'
        with:
          name: docker-image
          path: docker
          retention-days: 1

  publish-docker:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    steps:
      - name: Download docker image tar from artifacts
        uses: actions/download-artifact@v2
        with:
          name: docker-image
          path: docker

      - name: Load docker image from tar
        run: |
          cd docker
          docker load < image.tar

      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Docker push
        run: docker push ${{ env.IMAGE_NAME }}
